In [1]:
%config IPCompleter.greedy=True
import pandas as pd
import pickle
import datetime
import re
from imblearn.under_sampling import RandomUnderSampler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as pit
from jupyterthemes import jtplot
from sklearn.preprocessing import LabelEncoder
from tqdm import tqdm
import numpy as np

In [2]:
# compi = pd.read_csv('./csv/horse_compi.csv')
# compi.to_pickle('horse_compi.pickle')
compi = pd.read_pickle('horse_compi.pickle')
compi

                  レースID(新)  コンピ指数  コンピ順位
0       202205280401070101     53      7
1       202205280401070102     66      2
2       202205280401070103     65      3
3       202205280401070104     56      6
4       202205280401070105     60      4
...                    ...    ...    ...
761714  200701060801011212     47     11
761715  200701060801011213     44     12
761716  200701060801011214     43     13
761717  200701060801011215     53      7
761718  200701060801011216     56      5

[761719 rows x 3 columns]

In [3]:
allrace_peds_raceid = pd.read_pickle('allrace_peds_raceid.pickle')
# # allrace_peds_raceid.head()
# # merge = pd.merge(compi, allrace_peds_raceid, on='レースID(新)', how='inner')
# r = allrace_peds_raceid.reset_index()
# r['レースID(新/馬番無)'] = r['レースID(新/馬番無)'].astype(int)
# r = r.set_index('レースID(新/馬番無)')
# r.to_pickle('allrace_peds_raceid.pickle')

In [2]:
peds = pd.read_pickle('./all_peds.pickle')

In [3]:
all_r = pd.read_csv('./csv/all.csv')

,レースID(新),前走レースID(新),場所,距離,クラス名,出走頭数,着順,騎手,多頭出し,所属,...,走破タイム,着差,1角,2角,3角,4角,上り3F,上り3F順,賞金,付加賞金
0,202205150502081205,202204030902040710,東京,ダ1400,3勝,16,１,川田将雅,NaN,(栗),...,1.22.9,-0.1,NaN,NaN,3.0,3.0,35.7,7,1840,35.0
1,202205150502081212,202204170902081212,東京,ダ1400,3勝,16,２,坂井瑠星,NaN,(栗),...,1.23.0,0.1,NaN,NaN,1.0,1.0,36.1,9,740,10.0
2,202205150502081207,202204160902071011,東京,ダ1400,3勝,16,３,福永祐一,NaN,(栗),...,1.23.1,0.2,NaN,NaN,9.0,9.0,35.3,6,460,5.0
3,202205150502081215,202204160902071006,東京,ダ1400,3勝,16,４,武豊,NaN,(栗),...,1.23.5,0.6,NaN,NaN,12.0,11.0,35.1,3,280,0.0
4,202205150502081206,202203120702011115,東京,ダ1400,3勝,16,５,ルメール,NaN,(美),...,1.23.6,0.7,NaN,NaN,6.0,6.0,36.2,10,184,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
734493,200701060801010104,200612170903060116,京都,ダ1200,未勝利,16,12,武幸四郎,NaN,(栗),...,1.14.9,2.7,NaN,NaN,13.0,12.0,37.8,7,0,NaN
734494,200701060801010115,200612170903060409,京都,ダ1200,未勝利,16,13,川島信二,NaN,(栗),...,1.15.4,3.2,NaN,NaN,11.0,12.0,38.4,13,0,NaN
734495,200701060801010103,200607020804060504,京都,ダ1200,未勝利,16,14,赤木高太,NaN,(栗),...,1.15.9,3.7,NaN,NaN,16.0,15.0,38.4,13,0,NaN
734496,200701060801010114,200610140805030211,京都,ダ1200,未勝利,16,15,安部幸夫,NaN,(栗),...,1.16.6,4.4,NaN,NaN,5.0,6.0,40.6,16,0,NaN
734497,200701060801010107,200612090903030403,京都,ダ1200,未勝利,16,16,川田将雅,NaN,(栗),...,1.16.8,4.6,NaN,NaN,13.0,15.0,39.6,15,0,NaN

In [18]:
# r = pd.read_csv('./csv/raceid.csv')
# r = pd.merge(r, rp, on='レースID(新)', how='inner')
r

,レースID(新),前走レースID(新),場所,距離,クラス名,出走頭数,着順,騎手,多頭出し,所属,...,上り3F順,賞金,付加賞金,レースID(新/馬番無),スピード指数,コンピ一位指数,コンピ一位指数差,血統登録番号,コンピ前指数,コンピ後指数
0,202205150502081205,202204030902040710,東京,ダ1400,3勝,16,１,川田将雅,NaN,(栗),...,7,1840,35.0,2022051505020812,118,78.0,0.0,2018105954,0.0,3.0
1,202205150502081212,202204170902081212,東京,ダ1400,3勝,16,２,坂井瑠星,NaN,(栗),...,9,740,10.0,2022051505020812,113,78.0,8.0,2018105470,5.0,14.0
2,202205150502081207,202204160902071011,東京,ダ1400,3勝,16,３,福永祐一,NaN,(栗),...,6,460,5.0,2022051505020812,109,78.0,22.0,2017106572,14.0,1.0
3,202205150502081215,202204160902071006,東京,ダ1400,3勝,16,４,武豊,NaN,(栗),...,3,280,0.0,2022051505020812,108,78.0,23.0,2016104952,1.0,1.0
4,202205150502081206,202203120702011115,東京,ダ1400,3勝,16,５,ルメール,NaN,(美),...,10,184,0.0,2022051505020812,120,78.0,3.0,2018105334,3.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668259,200701060801010104,200612170903060116,京都,ダ1200,未勝利,16,12,武幸四郎,NaN,(栗),...,7,0,NaN,2007010608010101,102,78.0,31.0,2004102278,2.0,2.0
668260,200701060801010115,200612170903060409,京都,ダ1200,未勝利,16,13,川島信二,NaN,(栗),...,13,0,NaN,2007010608010101,93,78.0,33.0,2004103399,2.0,1.0
668261,200701060801010103,200607020804060504,京都,ダ1200,未勝利,16,14,赤木高太,NaN,(栗),...,13,0,NaN,2007010608010101,84,78.0,38.0,2004101085,1.0,0.0
668262,200701060801010114,200610140805030211,京都,ダ1200,未勝利,16,15,安部幸夫,NaN,(栗),...,16,0,NaN,2007010608010101,109,78.0,37.0,2004105239,1.0,1.0
668263,200701060801010107,200612090903030403,京都,ダ1200,未勝利,16,16,川田将雅,NaN,(栗),...,15,0,NaN,2007010608010101,90,78.0,35.0,2004101081,1.0,1.0

In [5]:
dev = pd.read_pickle('./horse_zi.pickle')
# dev.drop(['レースID(新/馬番無)'], axis=1, inplace=True)
dev

                    スピード指数
レースID(新)
200701060601010101      94
200701060601010102      91
200701060601010103     116
200701060601010104     114
200701060601010105      89
...                    ...
202205150703041202      95
202205150703041203     107
202205150703041204      94
202205150703041205      96
202205150703041206      89

[679699 rows x 1 columns]

In [6]:
r = pd.read_csv('./csv/raceid.csv')
r = pd.merge(allrace_peds_raceid, r, on='レースID(新)', how='inner')
r = r.set_index('レースID(新/馬番無)')

In [7]:
all_r = pd.read_csv('./csv/all.csv')

In [13]:
race_pass = pd.read_csv('./csv/race_pass5.csv')
race_pass

,レースID(新),コンピ一位指数,コンピ一位指数差,コンピ前指数,コンピ後指数,1走前着順,1走前賞金,1走前jockeyid,1走前コンピ指数,1走前コンピ順位,...,3走前3F位*3,3走前上り3F平均速度,3走前平均1Fタイム,3走前3F平均速度,3走前脚質,3走前A-3F差.1,3走前Ave-3F.1,平均着順,平均賞金,複勝率
0,201701290701060607,74.0,31.0,1.0,1.0,14.0,0.0,1038.0,42.0,13.0,...,0.94,60.00,59.67,59.83,12.03,後方,36.20,9.38,52.31,0.15
1,201010310303041003,73.0,18.0,1.0,6.0,11.0,0.0,1061.0,50.0,10.0,...,0.93,55.38,57.37,56.69,12.70,先行,37.65,8.92,62.50,0.25
2,201402231001060609,88.0,48.0,1.0,0.0,14.0,0.0,1030.0,47.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.00,0.00,0.00
3,201704020902041209,70.0,3.0,3.0,1.0,9.0,0.0,1018.0,67.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.50,0.00,0.00
4,201407200703060714,75.0,29.0,3.0,1.0,11.0,0.0,1130.0,52.0,7.0,...,0.96,56.99,56.62,56.74,12.69,後方,38.15,5.64,88.27,0.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
665059,201405240401070814,79.0,12.0,5.0,11.0,5.0,67.0,1093.0,52.0,7.0,...,1.07,56.84,62.25,59.42,12.12,逃げ,34.70,6.53,114.53,0.29
665060,202104170401031109,73.0,32.0,1.0,1.0,8.0,0.0,1135.0,40.0,16.0,...,0.98,55.96,56.18,56.10,12.83,後方,38.45,7.65,82.94,0.12
665061,201610160804050901,87.0,25.0,5.0,1.0,4.0,240.0,1115.0,66.0,3.0,...,0.92,60.17,60.20,60.19,11.96,先行,35.88,2.33,340.00,0.67
665062,201504110301010905,66.0,6.0,1.0,1.0,7.0,0.0,1140.0,60.0,4.0,...,0.78,60.00,60.25,60.10,11.98,中団,35.85,5.60,97.31,0.31
665063,201704150603070402,80.0,29.0,1.0,1.0,12.0,0.0,1151.0,50.0,8.0,...,1.01,62.07,56.19,57.83,12.45,後方,38.44,9.50,0.00,0.00

In [14]:
rp = race_pass[['レースID(新)', 'コンピ前指数', 'コンピ後指数']]

In [15]:
rp

                  レースID(新)  コンピ前指数  コンピ後指数
0       201701290701060607     1.0     1.0
1       201010310303041003     1.0     6.0
2       201402231001060609     1.0     0.0
3       201704020902041209     3.0     1.0
4       201407200703060714     3.0     1.0
...                    ...     ...     ...
665059  201405240401070814     5.0    11.0
665060  202104170401031109     1.0     1.0
665061  201610160804050901     5.0     1.0
665062  201504110301010905     1.0     1.0
665063  201704150603070402     1.0     1.0

[665064 rows x 3 columns]

In [9]:
r = pd.merge(all_r, race_pass, on='レースID(新)', how='inner')

In [48]:
# all_r = pd.read_csv('./csv/all_r.csv')
# compi = pd.read_pickle('horse_compi.pickle')
# r = pd.merge(all_r, compi, on='レースID(新)', how='inner')
# r = pd.merge(r, jt, on='レースID(新)', how='inner')
r = r.set_index('レースID(新)')
r.to_csv('./csv/all_r.csv')

In [12]:
z = pd.read_pickle('horseid.pickle')
r = pd.merge(r, z, on='レースID(新)', how='inner')
r.head()

,レースID(新),前走レースID(新),場所,距離,クラス名,出走頭数,着順,騎手,多頭出し,所属,...,上り3F,上り3F順,賞金,付加賞金,レースID(新/馬番無),スピード指数,コンピ一位指数,コンピ一位指数差,1走前着順,血統登録番号
0,202205150502081205,202204030902040710,東京,ダ1400,3勝,16,１,川田将雅,NaN,(栗),...,35.7,7,1840,35.0,2022051505020812,118,78.0,0.0,1.0,2018105954
1,202205150502081212,202204170902081212,東京,ダ1400,3勝,16,２,坂井瑠星,NaN,(栗),...,36.1,9,740,10.0,2022051505020812,113,78.0,8.0,11.0,2018105470
2,202205150502081207,202204160902071011,東京,ダ1400,3勝,16,３,福永祐一,NaN,(栗),...,35.3,6,460,5.0,2022051505020812,109,78.0,22.0,16.0,2017106572
3,202205150502081215,202204160902071006,東京,ダ1400,3勝,16,４,武豊,NaN,(栗),...,35.1,3,280,0.0,2022051505020812,108,78.0,23.0,5.0,2016104952
4,202205150502081206,202203120702011115,東京,ダ1400,3勝,16,５,ルメール,NaN,(美),...,36.2,10,184,0.0,2022051505020812,120,78.0,3.0,2.0,2018105334

In [50]:
# r = pd.merge(r, compi, on='レースID(新)', how='inner')
r['脚質'].value_counts()

中団     247676
後方     196698
先行     164819
逃げ      49347
ﾏｸﾘ      4907
Name: 脚質, dtype: int64

In [13]:
hi = pd.read_csv('./csv/horseid.csv')
hi.head()

             レースID(新)      血統登録番号
0  202205150502081205  2018105954
1  202205150502081212  2018105470
2  202205150502081207  2017106572
3  202205150502081215  2016104952
4  202205150502081206  2018105334

In [50]:
results.to_pickle('./pickle/all_merge_new.pickle')

In [25]:
share = pd.read_csv("./csv/fukusho_share.csv")
r = pd.merge(r, share, on='レースID(新)', how='inner')

In [57]:
# r = pd.read_csv('./csv/all_r.csv')
# r.drop_duplicates(['レースID(新)']).reset_index()
# r = r.set_index('レースID(新)')
r.to_csv('./csv/all_r.csv')

In [20]:
results = pd.read_pickle('./pickle/all_merge_new.pickle')

In [17]:
results = results.drop_duplicates(['前走レースID(新)']).reset_index()

In [30]:
results = results.set_index('レースID(新)')

In [15]:
peds = pd.read_pickle("all_peds.pickle")
results = r.copy()
results['血統登録番号'] = results['血統登録番号'].astype(str)
results = results.merge(peds, left_on='血統登録番号', right_index=True, how='left')
results['horse_id'] = results['血統登録番号']
results['horse_id'] = results['horse_id'].astype(int)
results.drop(['血統登録番号'], axis=1, inplace=True)

In [19]:
results.drop(['index'], axis=1, inplace=True)